# 1.1 Creating a Vector

## Solution - Use NumPy to create a one-dimensional array:

In [1]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])


In [2]:
print(vector_row)

[1 2 3]


In [3]:
print (vector_column)

[[1]
 [2]
 [3]]


# 1.2 Creating a Matrix

## Solution - Use NumPy to create a two-dimensional array:

In [4]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [5]:
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


### Cool Links
* [Matrix, Wikipedia](https://en.wikipedia.org/wiki/Matrix_(mathematics))
* [Matrix, Wolfram MathWorld](https://mathworld.wolfram.com/Matrix.html)

# 1.3 Creating a Sparse Matrix

## Solution - Create a sparse matrix:

In [11]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],[0, 1],[3, 0]])

print(matrix)

[[0 0]
 [0 1]
 [3 0]]


In [12]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


# 1.4 Selecting Elements

In [13]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [14]:
# Select second row, second column
matrix[1,1]

5

# 1.5 Describing a Matrix

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

(3, 4)

In [16]:
# View number of elements (rows * columns)
matrix.size

12

In [17]:
# View number of dimensions
matrix.ndim

2

# 1.6 Applying Operations to Elements

## Solution - Use NumPy’s vectorize:

In [19]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# 1.7 Finding the Maximum and Minimum Values

In [20]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [21]:
np.min(matrix)

1

### Discussion
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. This returns the results as a numpy array.  Using the axis parameter we can also apply the operation along a certain axis:

In [24]:
# Find maximum element in each column
# Axix 0 is the row
np.max(matrix, axis=0)

array([7, 8, 9])

In [25]:
# Find maximum element in each row
# Axix 0 is the row
np.max(matrix, axis=1)

array([3, 6, 9])

In [26]:
type(np.max(matrix, axis=1))

numpy.ndarray

In [27]:
## Solution - Use NumPy’s mean, var, and std:

# 1.8 Calculating the Average, Variance, and Standard Deviation

In [31]:
import math

In [28]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [29]:
# Return variance
np.var(matrix)

6.666666666666667

In [36]:
np.std(matrix)

2.581988897471611

### Discussion
Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis:

In [37]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

### This looks like the middle row, so lets try it with a different matrix

In [38]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [57, 85, 59]])

In [39]:
np.mean(matrix, axis=0)

array([20.66666667, 30.66666667, 22.66666667])

# 1.9 Reshaping Arrays

In [40]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Discussion
reshape allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns. The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., the same size). We can **see** the size of a matrix using size:

In [41]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [43]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Note: The actual shape is not changed, just how it was viewed:

In [48]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
matrix.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
matrix.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [49]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 1.10 Transposing a Vector or Matrix

In [50]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Discussion
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values:

In [51]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [52]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [54]:
newrv = np.array([[1, 2, 3, 4, 5, 6]]).T

print(newrv)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [55]:
type(newrv)

numpy.ndarray

In [56]:
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Discussion (Tim)
Note in the above, what gets shown: 
```
    array([....])
```    
may be different from what printed:
```
    [[1]
     [2]...
       ]
```

# 1.11 Flattening a Matrix (Two Ways)

In [58]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Alternatvies
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [61]:
# Again, just want to make sure these print the same.
matrix.flatten().shape

(9,)

In [62]:
matrix.reshape(1,-1).shape

(1, 9)

### Discussion (Tim)
Flatten transforms a matrix into a one-dimensional array.

Reshape will create a new row vector.

In [64]:
type(matrix.flatten())

numpy.ndarray

In [65]:
type(matrix.reshape(1,-1))

numpy.ndarray