# 1.1 Creating a Vector

## Solution - Use NumPy to create a one-dimensional array:

In [1]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])


In [2]:
print(vector_row)

[1 2 3]


In [3]:
print (vector_column)

[[1]
 [2]
 [3]]


# 1.2 Creating a Matrix

## Solution - Use NumPy to create a two-dimensional array:

In [4]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [5]:
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


### Cool Links
* [Matrix, Wikipedia](https://en.wikipedia.org/wiki/Matrix_(mathematics))
* [Matrix, Wolfram MathWorld](https://mathworld.wolfram.com/Matrix.html)

# 1.3 Creating a Sparse Matrix

## Solution - Create a sparse matrix:

In [7]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrixmatrix = np.array([[0, 0],[0, 1],[3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

ModuleNotFoundError: No module named 'scipy'